### ISSUE TITLE
Error in the function onAnyMeesage

### ISSUE THREAD

**Issue by valentinolopezbruno** [orkestral/venom#2813]
## Description
Hi.
When calling the onAnyMessage function in index.js it does not work directly and does not record the debug logs. I am currently working with version 5.1.0. 

[Description of the bug, When Issue Happens]

I only managed to solve it with this version: https://github.com/orkestral/venom/pull/2712 but when a message comes in, it is replicated in an infinite loop in my own chat.

## Environment

- **Venom version(s):** [ 5.1.0 --- https://github.com/orkestral/venom/pull/2712 ]
- **Browser:** [-]
- **OS:** [Windows 10]
- **Node version:** [Node 20]

## Steps to Reproduce

1. Clone lastest version
2. npm install venom-bot@5.1.0 (to note that the messages do not enter)
3. tryhttps://github.com/orkestral/venom/pull/2712

## Log Output

```
Error [TypeError]: window.WAPI.waitNewAcknowledgements is not a function
    at evaluate (evaluate at Whatsapp.initService (C:\VenomValen\venom\node_modules\venom-bot\dist\api\whatsapp.js:81:29), <anonymous>:14:12)
    at #evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:199:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:126:16)        
    at async IsolatedWorld.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:131:16)
    at async CdpFrame.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:363:20)
    at async CdpPage.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:751:20)
    at async Whatsapp.initService (C:\VenomValen\venom\node_modules\venom-bot\dist\api\whatsapp.js:81:13)
    at async C:\VenomValen\venom\node_modules\venom-bot\dist\api\whatsapp.js:47:13
Error [TypeError]: window.WAPI.waitNewAcknowledgements is not a function
    at evaluate (evaluate at Whatsapp.initService (C:\VenomValen\venom\node_modules\venom-bot\dist\api\whatsapp.js:81:29), <anonymous>:14:12)
    at #evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:199:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:126:16)        
    at async IsolatedWorld.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:131:16)
    at async CdpFrame.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:363:20)
    at async CdpPage.evaluate (C:\VenomValen\venom\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:751:20)
    at async Whatsapp.initService (C:\VenomValen\venom\node_modules\venom-bot\dist\api\whatsapp.js:81:13)
    at async C:\VenomValen\venom\node_modules\venom-bot\dist\controllers\initializer.js:348:13
```

## Your Code

```
// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');

venom
  .create({
    session: 'session-name' //name of session
  })
  .then((client) => start(client))
  .catch((erro) => {
    console.log(erro);
  });

function start(client) {
  client.onAnyMessage((message) => {
console.log("Enter")
    if (message.isGroupMsg === false) {
      client
        .sendText(message.from, 'Welcome Venom 🕷')
        .then((result) => {
          console.log('Result: ', result); //return object success
        })
        .catch((erro) => {
          console.error('Error when sending: ', erro); //return object error
        });
    }
  });
}
```

## Additional context / Screenshot
![image](https://github.com/user-attachments/assets/5e84a660-7b2a-4270-a0b1-56a93a66ee56)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ghayman** [comment]
Please try and install directly from venom/master branch.

We've had some trouble updating the npmjs library release.

**Comment by valentinolopezbruno** [comment]
I managed to solve it, thank you very much. I just had to install version 5.2.0. The problem now is that the messages are duplicated if the sender or the recipient has more than one Whatsapp session linked to that phone number.
