### ISSUE TITLE
Problems After New Releases

### ISSUE THREAD

**Issue by OrhanArslan** [orkestral/venom#658]
Many functions -including initializer- are not working properly after last releases. Please dont close the issue at least until base problems (eg. initializer) will be fixed.

**Comment by orkestral** [comment]
we performed tests on several OS and we did not detect any problem please before opening an issue perform tests in your environment such as deleting folder node_modules and package.json.lock and then an npm install

**Comment by OrhanArslan** [comment]
I have deleted folders that you said and then reinstall packages but it didn't work.

**Comment by adierebel** [comment]
Got this error after update to 3.0.6:
```
TypeError: browser.on is not a function
    at Object.<anonymous> (/home/hewatsap/node_modules/venom-bot/dist/controllers/initializer.js:199:29)
    at step (/home/hewatsap/node_modules/venom-bot/dist/controllers/initializer.js:44:23)
    at Object.next (/home/hewatsap/node_modules/venom-bot/dist/controllers/initializer.js:25:53)
    at fulfilled (/home/hewatsap/node_modules/venom-bot/dist/controllers/initializer.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
