### ISSUE TITLE
sendText  when first text is error

### ISSUE THREAD

**Issue by kingrootid** [orkestral/venom#1261]
from bot is a first chat to receiver
i got some error 
```
(node:855) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: n._find is not a function
    at https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:342945
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63784)
    at s (https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63995)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:64054
    at j (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:2:385573)
    at new g (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:2:376468)
    at https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63935
    at W._serverQuery (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:343309)
    at W._query (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:342436)
    at ExecutionContext._evaluateInternal (/Users/rw/Documents/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/Users/rw/Documents/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(Use node --trace-warnings ... to show where the warning was created)
(node:855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
i use 4.0.1 venom bot version

**Comment by mateuscdor** [comment]
verifique dentro do arquivo .json se sua versão realmente é:  4.0.1
se não estiver atualizando 
recomendo que você apague a pasta nodemodule e os arquivos .json e instale do zero.

**Comment by kingrootid** [comment]
I have checked for package.json already using 4.0.1 and I tried to remove node_modules and npm install but still the same

**Comment by HENRDS** [comment]
I have the same problem, I deleted node_modules, package-lock.json, and updated the venom version to 4.0.1 but no success

**Comment by matheusm821** [comment]
Estou com o mesmo problema!

**Comment by fernandopraise** [comment]
Estou com o mesmo problema, já apaguei o diretorio node_modules, e o arquivo package-lock.json e reinstalei novamente o venom, porem sem sucesso.

**Comment by AlexsandroZanella2** [comment]
I had resolved this using version 3.1.12

**Comment by fernandopraise** [comment]
3.1.12 ???? para qual ?

**Comment by fernandopraise** [comment]
@matheusm821 eu consegui, mudando o nome da sessão, assim vai scanear no qrcode novamente, e assim  funcionou o SendText

**Comment by matheusm821** [comment]
@fernandopraise Eu não consegui  apaguei a sessão completa esta dando o mesmo erro. testei na versão 3.1.12 e na versão atual.

**Comment by AlexsandroZanella2** [comment]
Try the following steps:
Delete node-modules folder,;
Delete package-lock;
Add in package.json:
"puppeteer": "^8.0.0",
"puppeteer-extra": "^3.1.18",
"puppeteer-extra-plugin-stealth": "^2.9.0";
Run npm i venom-bot@3.1.12;
Run npm cache clean --force; and
npm i

**Comment by AlexsandroZanella2** [comment]
> Same issue. Can't start a chat with a new contact unless they send me a message first even after I updated to 4.0.1. Got a fix for this? Thanks!

I'm using version 3.1.12 in production with a few dozen companies, and I don't have this problem in this version

**Comment by fernandopraise** [comment]
@AlexsandroZanella2 very good... thanks.

**Comment by iamedusm** [comment]
I have the same problem, with version 4.0.1

**Comment by miguelarcjr** [comment]
Estou obtendo o mesmo erro quando tento enviar uma mensagem para um telefone fixo com ddd 61

**Comment by diazzaid** [comment]
> from bot is a first chat to receiver i got some error
> 
> ```
> (node:855) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: n._find is not a function
>     at https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:342945
>     at Generator.next (<anonymous>)
>     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63784)
>     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63995)
>     at https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:64054
>     at j (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:2:385573)
>     at new g (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:2:376468)
>     at https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63935
>     at W._serverQuery (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:343309)
>     at W._query (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:342436)
>     at ExecutionContext._evaluateInternal (/Users/rw/Documents/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async ExecutionContext.evaluate (/Users/rw/Documents/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
> (Use node --trace-warnings ... to show where the warning was created)
> (node:855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> i use 4.0.1 venom bot version

this error is due to activating multi device
try disabling the feature
multi-device: false,

**Comment by marcus88santos** [comment]
> Try the following steps: Delete node-modules folder,; Delete package-lock; Add in package.json: "puppeteer": "^8.0.0", "puppeteer-extra": "^3.1.18", "puppeteer-extra-plugin-stealth": "^2.9.0"; Run npm cache clean --force; and Run npm i venom-bot@3.1.12; and npm i

Works for me!

**Comment by marcus88santos** [comment]
> > from bot is a first chat to receiver i got some error
> > ```
> > (node:855) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: n._find is not a function
> >     at https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:342945
> >     at Generator.next (<anonymous>)
> >     at t (https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63784)
> >     at s (https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63995)
> >     at https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:64054
> >     at j (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:2:385573)
> >     at new g (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:2:376468)
> >     at https://web.whatsapp.com/vendor1~bootstrap_qr.d4ef2d214939fc06cd93.js:2:63935
> >     at W._serverQuery (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:343309)
> >     at W._query (https://web.whatsapp.com/bootstrap_qr.ccb090b3a46e05558abd.js:56:342436)
> >     at ExecutionContext._evaluateInternal (/Users/rw/Documents/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
> >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> >     at async ExecutionContext.evaluate (/Users/rw/Documents/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
> > (Use node --trace-warnings ... to show where the warning was created)
> > (node:855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > (node:855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i use 4.0.1 venom bot version
> 
> this error is due to activating multi device try disabling the feature multi-device: false,

I set "muiltidevice: false", but no success

**Comment by marcus88santos** [comment]
For me this error occurs when trying to send message to non-existing contact. Same number, old version of venom (v 3.1.12) don't send the message and lastest version of venom (v 4.0.1) returns this error.

**Comment by andrerizzi** [comment]
Same error in sendText last version of venom with multidevice

**Comment by brainwares** [comment]
wapi functions: check-send-exists.js line 174

const storeChat = await window.Store.Chat.find(chatId);
change to:
const storeChat = await window.Store.Chat._find(chatId);

then rebuild wapi

hope it helps

**Comment by orkestral** [comment]
fixed in version 4.0.2
