### ISSUE TITLE
TypeError: this.page.on is not a function

### ISSUE THREAD

**Issue by Ramstin13** [orkestral/venom#2250]
hi, i am having this error after upgrading to 5.0.0

info:     [apps] Waiting... checking the browser...
info:     [apps:browser] Check chromium....
info:     [apps:browser-total] Checking the total bytes to download!
info:     [apps:browser] Chromium Finished result
info:     [apps:browser-total] Chromium completed result
info:     [apps] Browser successfully opened
info:     [apps] checking headless...
info:     [apps] headless option is active, browser hidden
info:     [apps] Checking page...
TypeError: this.page.on is not a function
    at new ListenerLayer (/home/venombot/node_modules/venom-bot/dist/api/layers/listener.layer.js:16:19)
    at new SenderLayer (/home/venombot/node_modules/venom-bot/dist/api/layers/sender.layer.js:66:9)
    at new RetrieverLayer (/home/venombot/node_modules/venom-bot/dist/api/layers/retriever.layer.js:8:9)
    at new GroupLayer (/home/venombot/node_modules/venom-bot/dist/api/layers/group.layer.js:10:9)
    at new UILayer (/home/venombot/node_modules/venom-bot/dist/api/layers/ui.layer.js:7:9)
    at new ControlsLayer (/home/venombot/node_modules/venom-bot/dist/api/layers/controls.layer.js:9:9)
    at new Whatsapp (/home/venombot/node_modules/venom-bot/dist/api/whatsapp.js:10:9)
    at Object.create (/home/venombot/node_modules/venom-bot/dist/controllers/initializer.js:162:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

i also tried installing chrome and setting useChrome: true, with same result.
previous version is working fine.

**Comment by Ramstin13** [comment]
i think the problem is originated by the presence of this file: \5.0.0\src\lib\wapi\webpack.config.cjs

**Comment by jonalan7** [comment]
remove the node_modules folder and the package-lock.json file and try to download again!
